"""
Code generated by ChatGPT
"""
import tkinter as tk
import random

window = tk.Tk() # Create the main window
window.geometry("500x300") # Set the size of the window

# window.wm_iconbitmap("purple.ico")
# window.update()

# Create a canvas widget to draw the figure on
canvas = tk.Canvas(window, width=500, height=200)

# Create a function to draw the figure on the canvas
def draw_figure():
    # Clear the canvas
    canvas.delete("all")
    # Get the width and height of the canvas
    width = canvas.winfo_width()
    height = canvas.winfo_height()
    # Draw a line on the canvas
    canvas.create_line(0, 0, width, height, fill="red", width=3)

# Call the draw_figure function to draw the initial figure
draw_figure()

# Bind the canvas to the <Configure> event to redraw the figure when the window is resized
canvas.bind("<Configure>", lambda event: draw_figure())

# Place the canvas on the window
canvas.pack()

# List of possible strings to choose from
choices = ["yes", "no", "maybe"]

# Function to generate a random choice
def random_choice():
    # Generate a random integer between 0 and 2
    random_index = random.randint(0, 2)
    # Use the random integer to select an item from the list of choices
    selected_choice = choices[random_index]
    # Set the text of the label to the selected choice
    choice_label.configure(text=selected_choice)

# Create a red button that triggers the random_choice function when clicked
random_button = tk.Button(window, text="Generate Random Choice", bg="red", fg="white", command=random_choice)

# Create a label to display the selected choice
choice_label = tk.Label(window, text="", font=("Helvetica", 36, "bold"))

# Place the button and the label on the window
random_button.pack()
choice_label.pack()

# Start the main event loop
window.mainloop()


